<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<NeutralLanguage>en</NeutralLanguage>
		<LangVersion>preview</LangVersion>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<IsPublishable>False</IsPublishable>
		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<RootNamespace>ExcelPRIME.RangeBench</RootNamespace>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="NewFolder\**" />
	  <EmbeddedResource Remove="NewFolder\**" />
	  <None Remove="NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.Cells" Version="26.3.0" />
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="EPPlus-LGPL" Version="4.5.3.13" />
		<PackageReference Include="FreeSpire.XLS" Version="14.2.0" />
		<PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.6.37125.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Excel_PRIME\Excel_PRIME.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\100mb.xlsx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Blank Data 1 Million Rows.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sampledocs-50mb-xlsx-file-sst.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sampledocs-50mb-xlsx-file.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\Excel_PRIME.Bench\Data\100mb.xlsx" Link="Data\100mb.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Include="..\Excel_PRIME.Bench\Data\Blank Data 1 Million Rows.xlsx" Link="Data\Blank Data 1 Million Rows.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Include="..\Excel_PRIME.Tests\Data\pivot-tables.xlsx" Link="Data\pivot-tables.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
