<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<NeutralLanguage>en</NeutralLanguage>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<IsTestProject>true</IsTestProject>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<RootNamespace>ExcelPRIME.Tests</RootNamespace>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Excel_PRIME.Bench\Data\Blank Data 1 Million Rows.xlsb" Link="Data\Blank Data 1 Million Rows.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\Excel_PRIME.Bench\Data\Blank Data 1 Million Rows.xlsx" Link="Data\Blank Data 1 Million Rows.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\Excel_PRIME.Bench\Data\sampledocs-50mb-xlsx-file-sst.xlsb" Link="Data\sampledocs-50mb-xlsx-file-sst.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\Excel_PRIME.Bench\Data\sampledocs-50mb-xlsx-file-sst.xlsx" Link="Data\sampledocs-50mb-xlsx-file-sst.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\Excel_PRIME.Bench\Data\sampledocs-50mb-xlsx-file.xlsb" Link="Data\sampledocs-50mb-xlsx-file.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\Excel_PRIME.Bench\Data\sampledocs-50mb-xlsx-file.xlsx" Link="Data\sampledocs-50mb-xlsx-file.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.3.0" />
		<PackageReference Include="AwesomeAssertions.Analyzers" Version="9.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.11.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="6.0.0">
			<TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="System.Linq.Async" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Excel_PRIME.Bench\Excel_PRIME.Bench.csproj">
			<Private>True</Private>
		</ProjectReference>
		<ProjectReference Include="..\Excel_PRIME.RangeBench\Excel_PRIME.RangeBench.csproj">
			<Private>True</Private>
		</ProjectReference>
		<ProjectReference Include="..\Excel_PRIMEXlsb.Bench\Excel_PRIMEXlsb.Bench.csproj">
			<Private>True</Private>
		</ProjectReference>
		<ProjectReference Include="..\Excel_PRIMEXlsb.RangeBench\Excel_PRIMEXlsb.RangeBench.csproj">
			<Private>True</Private>
		</ProjectReference>
		<ProjectReference Include="..\Excel_PRIME\Excel_PRIME.csproj">
			<Private>True</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\delete1.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\delete1.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\delete2.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\delete2.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Demo Column Types Strict OpenXMLSpreadSheet.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Demo Column Types Strict OpenXMLSpreadSheet.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Demo Column Types.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Demo Column Types.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\dynamic-named-range.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\dynamic-named-range.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\empty.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\empty.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Hidden.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Hidden.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\invalidfile.xlsx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\missingworkbook.xlsx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Data\missingworkbookrelatioship.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\missingworkbookrelatioship.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\multipleemptysheets.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\multipleemptysheets.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\multisheet1.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\multisheet1.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\named-range.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\named-range.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\pivot-tables.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\pivot-tables.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\SameKey.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\SameKey.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sample_file_bad.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sample_file_bad.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sample_file_good.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\sample_file_good.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\singlesheet.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\singlesheet.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\solver.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\solver.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\special-char.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\special-char.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\styledworkbook.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\styledworkbook.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\template.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\template.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\ValueTest.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\ValueTest.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\verysimple.xlsb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\verysimple.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
